/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;


import Donnees.CRapportVisite;
import Service.CMetierRV;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author camilletilmont
 */
public class JPanelListeRapport extends javax.swing.JPanel {

    /**
     * Creates new form JPanelListeRapport
     */
    public JPanelListeRapport() {
        initComponents();
        
    }
    
     protected CMetierRV metierListeRV;
      protected JTabbedPane panelParent;
      protected JPanelDetailRapport panelDetailRapport;
      protected JPanelConnexion panelCo;

    public JPanelConnexion getPanelCo() {
        return panelCo;
    }

    public void setPanelCo(JPanelConnexion panelCo) {
        this.panelCo = panelCo;
    }

    public JPanelDetailRapport getPanelDetailRapport() {
        return panelDetailRapport;
    }

    public void setPanelDetailRapport(JPanelDetailRapport panelDetailRapport) {
        this.panelDetailRapport = panelDetailRapport;
    }

    public JTabbedPane getPanelParent() {
        return panelParent;
    }

    public void setPanelParent(JTabbedPane panelParent) {
        this.panelParent = panelParent;
    }

    public CMetierRV getMetierListeRV() {
        return metierListeRV;
    }

    public void setMetierListeRV(CMetierRV metier) {
        this.metierListeRV = metier;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Praticien", "Motif Visite", "Bilan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("Nouveau Rapport");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Lire Rapport");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Se Deconnecter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Rafraichir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        getPanelParent().setSelectedIndex(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) getjTable2().getModel();
        
        getPanelDetailRapport().setCle(getjTable2().getSelectedRow());
        CRapportVisite rapportSelect = getMetierListeRV().getListeRapportVisite().get(getjTable2().getSelectedRow());
        
        getPanelDetailRapport().getMotifText().setText(rapportSelect.getMotifRapport());
        getPanelDetailRapport().getMotifText().setEditable(false);
        getPanelDetailRapport().getBilanText().setText(rapportSelect.getBilanRapport());
        getPanelDetailRapport().getBilanText().setEditable(false);
        getPanelDetailRapport().getDateLabel().setText(new SimpleDateFormat("dd/MM/yyyy").format(rapportSelect.getDateRapport().getTime()));
        getPanelDetailRapport().getNomVisiteurLabel().setText(rapportSelect.getVisiteurRapport().getNom());
        getPanelDetailRapport().getPraticienComboBox().hide();
        getPanelDetailRapport().getNomPra().setText(rapportSelect.getPraticienRapport().getNom() + " "+ rapportSelect.getPraticienRapport().getNom());
        getPanelDetailRapport().getMedocComboBox().hide();
        getPanelDetailRapport().getQteComboBox().hide();
        getPanelDetailRapport().getjButton3().hide();
        getPanelDetailRapport().getjButton2().hide();
        getPanelDetailRapport().getjButton5().hide();
        
        getPanelParent().setSelectedIndex(1);
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        refresh();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:  
        
        getjTable2().setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Praticien", "Motif Visite", "Bilan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        
        getPanelParent().insertTab("Connexion", null, panelCo, TOOL_TIP_TEXT_KEY, 0);
        getPanelParent().setEnabledAt(1, false);
        getPanelParent().setBackgroundAt(1, Color.darkGray);
        getPanelParent().setForegroundAt(1, Color.LIGHT_GRAY);
        getPanelParent().setEnabledAt(2, false);
        getPanelParent().setBackgroundAt(2, Color.darkGray);
        getPanelParent().setForegroundAt(2, Color.LIGHT_GRAY);
        getPanelParent().setSelectedIndex(0);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    public JTable getjTable2() {
        return jTable2;
    }

    public void setjTable2(JTable jTable2) {
        this.jTable2 = jTable2;
    }

    public void refresh(){
     int valueRefresh = getMetierListeRV().afficherRPVisiteurs();
        switch (valueRefresh){
            case 0 :
                
                break;
            case 2 :
                DefaultTableModel model = (DefaultTableModel) getjTable2().getModel();
                model.setRowCount(0);
                getMetierListeRV().getListeRapportVisite().forEach((rapport) -> {
                    model.addRow(new Object[]{new SimpleDateFormat("dd/MM/yyyy").format(rapport.getDateRapport().getTime()),
                        rapport.getPraticienRapport().getNom() + " " + rapport.getPraticienRapport().getPrenom(),
                        rapport.getMotifRapport(),rapport.getBilanRapport()});
                });
                break;
            default :
                
                break;
        
        }
    
    }
}
