/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import Service.CMetierRV;

/**
 *
 * @author camilletilmont
 */
public class JPanelDetailRapport extends javax.swing.JPanel {

    /**
     * Creates new form JPanelDetailRapport
     */
    public JPanelDetailRapport() {
        initComponents();
    }

    
     protected CMetierRV metierDetailRV;

    public CMetierRV getMetierDetailRV() {
        return metierDetailRV;
    }

    public void setMetierDetailRV(CMetierRV metier) {
        this.metierDetailRV = metier;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomVisiteurLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        motifText = new javax.swing.JTextField();
        bilanText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        echantillonTab = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        medicamentTab = new javax.swing.JTable();
        echantListLabel = new javax.swing.JLabel();
        medicListLabel = new javax.swing.JLabel();

        nomVisiteurLabel.setText("Nom Visiteur");

        dateLabel.setText("Date");

        motifText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motifTextActionPerformed(evt);
            }
        });

        bilanText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilanTextActionPerformed(evt);
            }
        });

        echantillonTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Echantillon", "Quantité"
            }
        ));
        jScrollPane1.setViewportView(echantillonTab);

        medicamentTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicament"
            }
        ));
        jScrollPane2.setViewportView(medicamentTab);

        echantListLabel.setText("Liste d'échantillons offerts");

        medicListLabel.setText("Liste médicaments abordés");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bilanText)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(motifText, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomVisiteurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                            .addComponent(echantListLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(medicListLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(motifText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomVisiteurLabel)))
                .addGap(18, 18, 18)
                .addComponent(bilanText, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(echantListLabel)
                    .addComponent(medicListLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void motifTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motifTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motifTextActionPerformed

    private void bilanTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilanTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bilanTextActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bilanText;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel echantListLabel;
    private javax.swing.JTable echantillonTab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel medicListLabel;
    private javax.swing.JTable medicamentTab;
    private javax.swing.JTextField motifText;
    private javax.swing.JLabel nomVisiteurLabel;
    // End of variables declaration//GEN-END:variables
}
